### PR TITLE
criando variavel para usar com commonJS

### PR DESCRIPTION
**Pull request by hugodutra**
Rapha,

I created a waterfall method in window to be able to use commonJS's require.

### CODE REVIEW

**Comment by israelst** [comment]
Hello @hugodutra, `waterfall` is already in the global namespace. What is your goal with this code?

**Comment by hugodutra** [comment]
Hey, @israelst 

Waterfall doesn't support export for commonJS so I had to explicit create this namespace on window to use it with Browserify Shim.

I'm shure if I was clear enough. :/

If you have anymore doubts or tips, please ask/talk.

**Comment by raphamorim** [comment]
guys, 

@hugodutra I think waterfall.js can't be loaded in the current context which you initialize the commonjs requires; a prove of what I'm talking about: Is that you solve this problem using `window`.

This is a wrong approach. 

You should be verify if waterfall exists in that context, if exists. The problem probably can be solved checking `module` and export. 

I'll solve this issue til' this weekend :)

**Comment by hugodutra** [comment]
I'll try a different approach here too, @raphamorim .

Thanks, for the feedback guys :)

**Comment by israelst** [comment]
@hugodutra, thank you for your time. :)

**Pull request closed without merging**
