### PR TITLE
add one more config property and update it

### PR DESCRIPTION
**Pull request by Cecilina**
With default 3, I got following display
default_3
After update the code. Here is the results.
with_additional_property

Thanks!

### CODE REVIEW

**Comment by raphamorim** [comment]
I see,
Predefine grid can be a option, what do you think @israelst?

**Comment by israelst** [comment]
@Cecilina Hello!

I didn't get why `smallerColumnLen` needs to be a parameter, given that we are already calculating the quantity of elements that fit in a row. Could you clarify it?

Thanks for you time.

**Comment by israelst** [comment]
@Cecilina, please take a look at #29. If it solves your problem we can merge it after your contribution at `develop`. What do you think?

**Comment by israelst** [comment]
@Cecilina, I'm closing it for now. Let me know if this PR doesn't solve your issue. 

Thank you for your time.

**Pull request closed without merging**
