### PR TITLE
Responds to window resize

### PR DESCRIPTION
**Pull request by diegohaz**

### CODE REVIEW

**Comment by raphamorim** [comment]
I maded some changes to support IE8 
Merged in another branch https://github.com/raphamorim/waterfall.js/pull/10

**Comment by israelst** [comment]
Is there a good reason to add this responsibility to `waterfall` itself? It already calculates the position of the elements inside a container, which is enough, I think.

We should not limit when the user may want to run the calculation. If one should refresh positions during window resize, may explicitly do that:

```js
window.addEventListener('resize', function () { waterfall(container); });
```

Or rerun `waterfall` in any other moment. Moreover, it avoids `arguments.callee` (e8f6d391) anti-pattern and simplify the code.

Other solution may create an OO api to encapsulate the `container`. But, in my opinion, it is too much abstraction for all use cases I can imagine.

**Comment by raphamorim** [comment]
Yeah, this is true.
Personally I do not like this output, too. But to solve a common problem, I took a merge. I think your very valid comment.

Perhaps one solution is to deliver responsive and one without.

**Comment by raphamorim** [comment]
`Other solution may create an OO api to encapsulate the container`
Yeah

**Comment by diegohaz** [comment]
For me, responsiveness is a must-have because I always want to handle the device orientation swap. But it makes much more sense to do that outside the waterfall function, like you said: 
```javascript
window.addEventListener('resize', function () { waterfall(container); });
```
I think the better solution is to just add this to README (it's not so obvious if you don't read the code). :)

**Pull request merged**
