### PR TITLE
Implements Tests and rewrite the codebase using ES6 (related to the issues #33 #3)

### PR DESCRIPTION
**Pull request by thiamsantos**
- Write tests using [Mocha](http://mochajs.org/), [Karma](http://karma-runner.github.io/1.0/index.html), [Assert](https://nodejs.org/api/assert.html) and [PhantomJS](http://phantomjs.org/). I was able to reach code coverage of 100% :tada:, so will be a good thing integrate the project with [coveralls](https://coveralls.io/).

coverage

- Rewrite the codebase using ES6.
- Add a build step for bundling three different versions of the module using [rollup](http://rollupjs.org/). A CommonJS version is expose through the property main on the `package.json`, an ES6 version is exposed through the [property module](https://github.com/rollup/rollup/wiki/pkg.module) on the `package.json` and also a umd version will be available at [unpkg](https://unpkg.com/) after this PR was accepted and ublished to npm.
- Add [node gitignore](https://github.com/github/gitignore/blob/master/Node.gitignore).
- Add a visual test example to see waterfall in action. Was used the same example available at the [project page](http://raphamorim.io/waterfall.js/).
- Add git hooks with a help from husky to:
    1. Prevent commits that doesn't follow the [code style](http://standardjs.com/).
    2. Always build the files before commiting.
    3. Prevent commits that have bronken tests.
- Add a npm script to run the build, test and the visual at watch mode. You can just type `npm start`.

### CODE REVIEW

**Comment by raphamorim** [comment]
Ref #34 #33 
Nice @thiamsantos, I'll review it tonight 👍

**Comment by thiamsantos** [comment]
Any thoughts @raphamorim?

**Comment by raphamorim** [comment]
I'm start reviewing it now, sorry by delay

I have some questions to proceed:
- Why to use ES6? (Only to know)
- Why it generate two files: `cjs` and `umd` version? Why it? How bower will understand it?
- Can you add Nodejs 7 in `travis.yml`? 
- If you're already using ES6 notation, can you test `import` cases too?

Also nice job testing UI behavior and remaining waterfall size after transpile it (I believe Rollup was a good choice)

**Comment by thiamsantos** [comment]
Thanks for taking time to review it @raphamorim!!

#### Why to use ES6?
ES6 provide some improvements on the syntax. Since a refactor was needed to implement the unit tests, why not use ES6 in that refactor?

#### Why it generate two files: cjs and umd version? Why it? How bower will understand it?
The cjs version is handled by npm when you type `require('waterfall.js')`. And the UMD version is used when you just embed the script on the browser (maybe using unpkg). For bower is needed to specify the [`main` property](https://github.com/bower/spec/blob/master/json.md#main) on `bower.json` pointing to the UMD version (I forgot to do that :grin:).

#### Can you add Nodejs 7 in travis.yml?
Sure. I will add the [latest stable Node.js release](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Available-Versions) to travis.yml.

#### If you're already using ES6 notation, can you test `import` cases too?
The `import` statement was not working just because the `main` property on `package.json` was pointing to a [file that did not exist](https://github.com/raphamorim/waterfall.js/blob/master/package.json#L5).

**Comment by thiamsantos** [comment]
On second thought the `cjs` version is actually not necessary, because the `umd` version is 'universal' and works well with CommonJS modules. So I can remove the `cjs` a leave just the `umd` version and the `ES6` version. What do you think @raphamorim? I can commit that?

**Comment by thiamsantos** [comment]
The [travis test on node v7.5.0](https://travis-ci.org/raphamorim/waterfall.js/jobs/203156916) failed. It seems to be a [problem related to yarn not building karma-phantomjs-launcher](https://github.com/karma-runner/karma-phantomjs-launcher/issues/120).

**Comment by thiamsantos** [comment]
Any thoughts @raphamorim?

**Pull request closed without merging**
